- name: 'Create and Manage Users'
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: 'Create User Account'
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'present'
        shell: '/bin/bash'
      when: user_create = 'yes'  